# Change these first
owner: EXStevens # Your GitHub organization or username, where this repository lives
repo: Up-Monitor # The name of this repository

sites:
  - name: Seattle Node
    check: "tcp-ping"
    url: $SEATTLE_NODE
  - name: Navigation
    url: https://nav.explorercs.com
  - name: Drive Proxy
    url: https://drive.explorercs.com
  - name: Blog
    url: https://cstevens.cc
  - name: Script CDN
    url: https://script.expcs.net
  - name: Gravatar CDN
    url: https://gravatar.expcs.net

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.explorercs.com
  baseUrl: /
  logoUrl: https://raw.githubusercontent.com/EXStevens/Up-Monitor/master/assets/cloud.svg
  name: ECS Service Status
  introTitle: The Status is shown below.
  introMessage:
  navbar:
  theme: night



# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
